server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://ewgf13uiynnisl88:lwc45bwqeae13lg3@y06qcehxdtkegbeb.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/hjyxht1xlcuo0nc9

#    ${JAWSDB_URL}
  jpa:
    hibernate:
      ddl-auto=update: create
    database-platform: org.hibernate.dialect.MySQL57Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

