server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://sammysql.mysql.database.azure.com/author?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: samrjonesdev@sammysql
    password: codegud24/7
#    ${JAWSDB_URL}
  jpa:
    hibernate:
      ddl-auto=update: create
    database-platform: org.hibernate.dialect.MySQL57Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

