server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${JAWSDB_URL}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

